package.json
src/client/webpack.config.babel.js
src/server/plugins/webpack-config/index.js

Start using tagged version 0.1.0.

Use first specific version of nhsuk-frontend

---

.eslintrc.json
package.json
src/__mocks__/node-ews.js
src/__tests__/lib/send-exchange-email.js
src/__tests__/plugins/nunjucks/functions.js
src/__tests__/plugins/register-form/summary-step.js
src/server/plugins/nunjucks/functions.js
src/server/plugins/nunjucks/index.js
src/server/plugins/register-form/steps/summary.js
src/server/templates/email/registration-summary.njk
src/server/templates/register-form/step.njk
src/server/templates/register-form/summary.njk
yarn.lock

- Render email from template
- Display form date on summary page

Summary page and Email template

---

src/server/index.js
src/server/plugins/getaddressio/index.js

@s-block what do you think of this instead?

make routes exposure configurable instead

---

package.json
src/client/js/index.js
src/client/js/modules/label-focus.js
src/client/js/modules/label-select.js
src/client/styles/base.scss
src/client/styles/components/_form-label.scss
src/client/styles/components/_form-multiple-choice.scss
src/client/styles/components/_form-textbox.scss
src/client/styles/variables.scss
src/server/plugins/nunjucks/index.js
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/contact-email.js
src/server/plugins/register-form/steps/contact-telephone.js
src/server/plugins/register-form/steps/current-gp.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/date-of-birth.js
src/server/plugins/register-form/steps/home-address.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previous-address.js
src/server/plugins/register-form/steps/previous-name.js
src/server/plugins/register-form/steps/your-name.js
src/server/templates/_components/form-multiple-choice.njk
src/server/templates/_components/form-textbox.njk
src/server/templates/index.njk
src/server/templates/register-form/step.njk
yarn.lock

This adds a few things for the frontend style.
- Links the register journey from the start page
- Adds support for component based loading in nunjucks
- Adds initial form components (textbox/multiple choice)
- Uses new form components in current steps

Initial frontend structure

---

src/client/styles/base.scss
src/client/styles/components/_button.scss
src/client/styles/components/_form-group.scss
src/client/styles/components/_form-label.scss
src/client/styles/components/_form-title.scss
src/client/styles/components/_summary.scss
src/server/plugins/register-form/steps/summary.js
src/server/templates/_components/form-multiple-choice.njk
src/server/templates/register-form/step.njk
src/server/templates/register-form/summary.njk

Adds basic style to step pages and check your details screen.

Check your details and step styles

---

src/__tests__/plugins/register-form/common.js
src/__tests__/plugins/register-form/name-step.js
src/server/plugins/register-form/index.js
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-email.js
src/server/plugins/register-form/steps/contact-telephone.js
src/server/plugins/register-form/steps/current-gp.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/date-of-birth.js
src/server/plugins/register-form/steps/home-address.js
src/server/plugins/register-form/steps/index.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previous-address.js
src/server/plugins/register-form/steps/previous-name.js
src/server/plugins/register-form/steps/summary.js
src/server/plugins/register-form/steps/your-name.js

I have added the concept of `checkApplies` as a possible key in the
step object.
If it is defined then the previous step, when trying to decide where to
send you next, will run that check and pass in the contents of the
cookie.
This check can return false and it will be skipped or true and it will
then be redirected to.

Feature/branching journey: Add way to depend on the result of another step 

---

Dockerfile
README.md
bin/dev.sh
bin/prod.sh
docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml
package.json
src/server/index.js
src/server/plugins/disable-http/index.js

Also change the prod docker-compose file to use npm instead of
yarn as using yarn to run the npm scripts was causing errors while
running inside docker

Optimise the npm build script

---

package.json
src/client/styles/components/_button.scss
yarn.lock

This update the frontend package which uses the new colour palette
and includes support for service title which this app will need
to use.

Update NHSUK Frontend package

---

src/server/plugins/register-form/index.js
src/server/plugins/register-form/steps/allergies-details.js
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-email.js
src/server/plugins/register-form/steps/contact-telephone.js
src/server/plugins/register-form/steps/current-medication-details.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/date-of-birth.js
src/server/plugins/register-form/steps/home-address.js
src/server/plugins/register-form/steps/nhs-number-details.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previous-address.js
src/server/plugins/register-form/steps/previous-name.js
src/server/plugins/register-form/steps/previously-registered.js
src/server/plugins/register-form/steps/summary.js
src/server/plugins/register-form/steps/your-name.js
src/server/templates/register-form/step.njk

This passes a url to the step view to support initial "back"
functionality for the steps.
It uses the `checkApplies` function to check whether the previous
step in the order applies, if not, it will continue.

Add initial support for "back" button

---

src/client/styles/base.scss
src/client/styles/components/_panel.scss
src/client/styles/units/_tables.scss
src/server/plugins/nunjucks/index.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-telephone.js
src/server/plugins/register-form/steps/current-gp.js
src/server/plugins/register-form/steps/index.js
src/server/plugins/register-form/steps/medical-history.js
src/server/plugins/register-form/steps/registered-address-details.js
src/server/plugins/register-form/steps/registered-address.js
src/server/plugins/register-form/steps/registered-name-details.js
src/server/plugins/register-form/steps/registered-name.js
src/server/templates/_includes/current-address.njk
src/server/templates/_includes/current-name.njk
src/server/templates/email/registration-summary.njk
src/server/templates/register-form/step.njk
src/server/templates/register-form/summary.njk

This pull request covers off a few minor changes to the journey to make sure it starts to match the prototype that has been tested so far.
It:
- changes telephone number to required
- Adds a step to collect basic medical history
- Refactors the steps around previous GP registration
- improves the check your details and confirmation email data playback

Journey tweaks

---

.eslintignore
src/client/js/vendor/polyfills/details.polyfill.js
src/client/webpack.config.babel.js
src/server/templates/index.njk

This adds the initial start page copy for the service.
This should be a temporary measure as the ideal pattern for services
is to have a start page live on NHS.UK and then take you straight
into the transaction part of the service.

Add basic start page copy

---

docs/architecture/decisions/0003-use-persistant-cookies.md
src/server/config/cookies.js

merge this to accept ARD#3 with session cookies. 
This will also change the app to use session cookies

Accept ADR#3 with Session Cookies Decision

---

docs/architecture/decisions/0003-use-persistant-cookies.md

Don't merge this as it's just a draft:
If you decide to use persistent cookies then merge PR #28
or if you decide to go for session cookies then merge PR #30

Raise ADR for cookies

---

src/client/styles/base.scss
src/client/styles/objects/_reading-width.scss
src/client/styles/trumps/_headings.scss
src/server/plugins/start-and-end/index.js
src/server/templates/end.njk

This adds the basic content for the transactions completion step.
Will need to be expanded to include the practice where the user
registered and the contact details for that practice.

Add basic end page content

---

package.json
src/__tests__/meta/cookies.js
yarn.lock

This ensures that the request made in test receives adequate response.
Fixes #35

Fix test to ensure the request is successful

---

.gitmodules
.travis.yml

Reverts nhsuk/register-with-a-gp-beta-web#44

Revert ":boom: Initial deployment config"

---

.dockerignore
Dockerfile

- Use specific version of node
- Use alpine image for smaller image
- Use unprivileged user

Use alpine image

---

package.json
yarn.lock

Closes #50
https://greenkeeper.io/

chore(package): update style-loader to version 0.16.1

---

src/__tests__/plugins/nunjucks/filters.js

Tests for new nl2br nunjucks filter

---

README.md
package.json
src/__tests__/plugins/register-form/summary-step.js
src/server/plugins/register-form/steps/summary.js
yarn.lock

This gets the practice email address from the environment variables
and uses that as the email send method.
It checks that the practice is in the accepted list and then converts
the key to a constant format so that it can get the value of the
email for that practice.
The email addresses will be stored as environment variables as the
emails provided my not be for public use.

Get practice email

---

src/server/plugins/register-form/steps/armed-enlist-date.js
src/server/plugins/register-form/steps/armed-staff-number.js
src/server/plugins/register-form/steps/index.js
src/server/plugins/register-form/steps/previously-armed.js
src/server/templates/email/registration-summary.njk
src/server/templates/register-form/summary.njk

https://trello.com/c/Fr4JSKdz/221-add-armed-forces-loop

Armed force loop added

---

docker-compose.dev.yml
src/__tests__/plugins/nunjucks/filters.js
src/server/plugins/nunjucks/filters.js
src/server/plugins/nunjucks/index.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-email.js
src/server/plugins/register-form/steps/contact-telephone.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/medical-history.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previously-armed.js
src/server/templates/register-form/step.njk

This PR adds a way to provide the user with an explanation for why you're asking for information in each step.

Progressive Disclosure

---

src/client/styles/base.scss
src/client/styles/components/_form-dropdown.scss
src/server/plugins/register-form/steps/your-name.js
src/server/templates/_components/form-dropdown.njk
src/server/templates/register-form/step.njk

Include Title field as dropdown with following options:
Mr
Ms
Mrs
Miss
Dr
Prof

Name title

---

package.json
src/__tests__/plugins/register-form/home-address.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/home-address-lookup-choose.js
src/server/plugins/register-form/steps/home-address-lookup.js
src/server/plugins/register-form/steps/index.js
src/server/templates/register-form/address-choose-step.njk
src/server/templates/register-form/step.njk
yarn.lock

This gives the user an opportunity to lookup their address
and an escape hatch if they just want to type it

Allow home address lookup

---

src/server/index.js
src/server/plugins/metrics/index.js

Emit the response log in a more structured way.
Plus put response time info in header.

New metrics log

---

src/shared/lib/joi-full-date-validator.js
yarn.lock

dob bug fixed

---

src/server/plugins/register-form/steps/summary.js
src/server/plugins/start-and-end/index.js
src/shared/lib/send-exchange-email.js

Practice should be coming from url everywhere through the process.

fixing practice issues at email and end page

---

src/server/templates/practices/end/default.njk

Content fixes to confirmation screen template

---

data/practices.json

Change based on '2i' content review - updated phone number format for Wallington to match content style (020 8XXX XXXX not 0208 XXX XXXX).

Content update to practices.json

---

src/server/plugins/register-form/steps/current-gp-address.js

Change based on '2i' content review - changed question and first text box label so it's clear that we're asking about the name and address of the GP practice, not the individual GP.

Content fix to current current-gp-address.js

---

src/shared/lib/send-exchange-email.js

Catch an error when calling ews.run and log into console.

error log added

---

tests/jmeter-performance/register-with-a-gp.jmx

Initial performance test against staging env

Initial Jmeter performance test

---

src/client/styles/base.scss
src/client/styles/fonts/_frutiger.scss

Manual override on styles where font-family was previously set.

frutiger font added

---

data/practices.json

Update details for the Wolds Practice

Update address format and phone number

---

data/practices.json
src/server/plugins/nunjucks/index.js
src/server/templates/practices.njk

Added a new environment variable to separate the different environments in application.
One property in practices.json to set the practice available to display.

test practice removed from production and APP_ENV implemented

---

src/__tests__/plugins/register-form/summary-handler.js
src/server/plugins/register-form/steps/summary.js

Checking the existing steps at summary page and redirects to first step if last step hasn't been finished.

step check with unittest

---

src/client/styles/base.scss
src/client/styles/widget/_widget.scss
src/server/index.js
src/server/plugins/widget/index.js
src/server/templates/layouts/widget.njk

A new fixed size page created.
It can be used in an iframe on other sites backlink to register-with-a-gp-beta-web

widget page created

---

src/client/styles/widget/_widget.scss
src/server/templates/layouts/widget.njk

styling separated for widget button so it won't interfere with start button.

changed button style for widget button

---

src/server/templates/register-form/step.njk
yarn.lock

code changes for below task.
Styling: Reposition 'Back' link

Ht ui backlog

---

src/server/plugins/register-form/steps/contact-details.js
src/server/plugins/register-form/steps/date-of-birth.js
src/server/templates/_components/form-numeric.njk
src/server/templates/_components/form-tel.njk
src/server/templates/register-form/step.njk

Number field to enable numeric keypad for mobile.

created number field for html5

---

src/server/templates/email/registration-summary-html.njk
src/server/templates/register-form/summary.njk

The email template has been rewritten based on on the summary page.

email template rewrite

---

src/client/styles/base.scss
src/client/styles/components/_form-multiple-choice.scss
src/client/styles/components/_layout.scss
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previously-armed.js
src/server/plugins/register-form/steps/previously-registered.js
src/server/plugins/register-form/steps/registered-address.js
src/server/plugins/register-form/steps/registered-name.js
src/server/templates/_components/form-radio-horizontal.njk
src/server/templates/register-form/registered-address.njk
src/server/templates/register-form/registered-name.njk
src/server/templates/register-form/step.njk

reposition of radio y/n buttons
Yes/ no type radio buttons are positioned horizontally.
for that i have introduced a new component form-radio-horizontal

reposition of radio y/n buttons

---

src/client/styles/components/_button.scss
src/server/templates/register-form/current-gp.njk
src/server/templates/register-form/registered-address.njk
src/server/templates/register-form/registered-name.njk
src/server/templates/register-form/step.njk

All 'back' links are moved to top of page

reposition of back link

---

src/client/styles/components/_form-multiple-choice.scss

reposition of y/n radio button for mobile(horizontal layout)

reposition of y/n radio button for mobile(horizontal layout)

---

src/client/styles/components/_layout.scss

footer padding changes done as per guideline doc

footer padding changes done as per guideline doc

---

src/server/templates/layouts/widget.njk

Content edited in backlink widget page

widget text amended

---

rancher-config/docker-compose.yml

Reverts nhsuk/register-with-a-gp-beta-web#226

Revert "Use ES image as part of stack"

---

src/client/styles/base.scss
src/client/styles/components/_header.scss
src/client/styles/fonts/_frutiger.scss
src/server/static/BETA.svg
src/server/templates/layouts/base.njk

header styling done as per sketch.

Header styling

---

src/client/styles/components/_header.scss
src/client/styles/components/_layout.scss
src/server/templates/practices/start/default.njk

css fixes done for mobile layout

layout fixes for mobile

---

src/__tests__/plugins/getaddressio/index.js
src/client/js/modules/address-ajax.js
src/client/styles/base.scss
src/client/styles/components/_address-lookup.scss
src/client/styles/components/_layout.scss
src/client/styles/fonts/_frutiger.scss
src/server/plugins/getaddressio/index.js
src/server/plugins/register-form/steps/home-address-lookup.js
src/server/templates/register-form/address-lookup.njk

Fixed the 500 error and unit testing.
Nested fields added to manual form.
Styling implemented.

Address lookup styling

---

src/client/styles/components/_form-dropdown.scss
src/client/styles/components/_form-label.scss
src/client/styles/components/_form-multiple-choice.scss
src/client/styles/components/_form-textbox.scss
src/client/styles/components/_layout.scss
src/client/styles/fonts/_frutiger.scss
src/server/templates/_components/form-allergies-nested-radio.njk
src/server/templates/_components/form-current-medication-radio.njk
src/server/templates/_components/form-nested-inline.njk

1. font size change for mobile
2. + symbol added for add new element link
3. padding between back link and page title is reduced

Design refresh  styling

---

src/server/templates/email/registration-summary-html.njk
src/server/templates/register-form/summary.njk

Missing address from summary and email template

fixed missing address from summary and email

---

src/server/plugins/register-form/steps/index.js
src/server/templates/register-form/address-lookup.njk

Js errors on address-lookup page has been fixed.

frontend js errors fixed

---

src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/home-address-lookup.js

Fixed the template value order in postHandlerfactory

template value for posthandlerfactory

---

src/client/js/modules/address-ajax.js
src/server/plugins/getaddressio/index.js
src/server/templates/register-form/address-lookup.njk

Address lookup with housenumber fixed
Display the postcode for selected address
Display the confirmation if address result is one line only

finding address with housenumber plus postcode display

---

src/server/plugins/register-form/steps/medical-history.js
src/server/templates/_components/form-nested-inline.njk

Fixed double initialize input problem

Double initialise input nested fields problem on medical history step 

---

src/__tests__/helpers/index.js

updated gp-lookup mock data

---

src/server/templates/email/registration-summary-html.njk
src/server/templates/email/registration-summary.njk

Missing address details displayed on email

Address details fixed on email

---

src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-details.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previously-armed.js

Some content was disappeared after throw validation errors. I added new parameters for `postHandlerFactory` and fixed individual steps.

Fixed: Disappeared content after validation 

---

src/server/plugins/nunjucks/index.js
src/server/plugins/register-form/steps/common.js
src/server/templates/_components/form-submitrow.njk
src/server/templates/register-form/address-lookup.njk
src/server/templates/register-form/registered-address.njk
src/server/templates/register-form/registered-name.njk
src/server/templates/register-form/step.njk

Text of Continue button changed to Done when when user is from Summary page

Done button

---

src/client/js/modules/address-ajax.js
src/client/styles/components/_confirm-block.scss
src/server/templates/register-form/address-lookup.njk

"Reset" text link changed to button for accessibility

reset text changed to button

---

src/client/js/index.js
src/client/js/modules/address-ajax.js
src/server/templates/layouts/base.njk
src/server/templates/register-form/address-lookup.njk
src/server/templates/register-form/registered-address.njk
src/server/templates/register-form/registered-name.njk
src/server/templates/register-form/step.njk

Added button role to disclosure summary

Disclosure accessibility

---

src/server/templates/_components/form-nested-gp-lookup.njk
yarn.lock

Replaced "reset" text to button for better accessibility

Reset button on GP lookup

---

src/server/templates/_components/form-nested-gp-lookup.njk
yarn.lock

"Find surgery" to be a button instead of tag

Find surgery button is a button not <a> tag

---

src/client/styles/components/_layout.scss
src/client/styles/fonts/_frutiger.scss
src/server/plugins/register-form/steps/date-of-birth.js
src/server/templates/register-form/step.njk
yarn.lock

Added hint block for step base template.

Added hint block for step templates 

---

src/__tests__/plugins/register-form/name-step.js
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/common.js
src/server/plugins/register-form/steps/contact-details.js
src/server/plugins/register-form/steps/countries-and-town.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/gender.js
src/server/plugins/register-form/steps/home-address-lookup.js
src/server/plugins/register-form/steps/nhs-number.js
src/server/plugins/register-form/steps/previously-armed.js
src/server/plugins/register-form/steps/previously-registered.js
src/server/plugins/register-form/steps/registered-address-details.js
src/server/plugins/register-form/steps/registered-address.js
src/server/plugins/register-form/steps/registered-name-details.js
src/server/plugins/register-form/steps/registered-name.js
src/server/plugins/register-form/steps/your-name.js
src/server/templates/_components/error-summary.njk
src/server/templates/_components/form-dropdown.njk
src/shared/lib/joi-full-date-validator.js
src/shared/lib/joi-nhs-number-validator.js
yarn.lock

- Added new step validation error messages for induvial steps

New step validation messages

---

src/client/styles/fonts/_frutiger.scss

reset link font changed to frutiger

reset link font changed to frutiger

---

src/server/plugins/register-form/steps/your-name.js

title field default value - select

title field default value - select

---

src/server/templates/_components/form-dropdown.njk

- Fixed dropdown component selected value issue

Dropdown component fixes

---

README.md

Acceptance test documentation (Linux / Mac) in Readme

readme updated for acceptance test

---

src/__tests__/plugins/nunjucks/filters.js
src/server/plugins/nunjucks/filters.js
src/server/plugins/register-form/steps/date-of-birth.js
src/server/templates/_components/error-summary.njk
src/server/templates/_components/form-numeric.njk
src/server/templates/register-form/step.njk
src/shared/lib/joi-full-date-validator.js

Date of Birth error messages and field highlight fixed

DoB error messages and behaviour changed

---

src/client/js/modules/address-ajax.js

The manual address disclosure has been removed after address selected

manual address disclosure removed

---

src/client/styles/components/_form-textbox.scss
src/server/plugins/register-form/steps/allergies.js
src/server/plugins/register-form/steps/current-medication.js
src/server/plugins/register-form/steps/medical-history.js
src/server/templates/_components/form-allergies-nested-radio.njk
src/server/templates/_components/form-current-medication-radio.njk
src/server/templates/_components/form-textbox.njk

- Changed recursive nested input field to textarea on current medication, allergies and medical history steps.

Nested field changes

---

src/__tests__/plugins/register-form/acceptance/register_gp_form_test.js
src/client/js/modules/gp-autocomplete.js

Disabled autocomplete functionality for gp-lookup

Disabled autocomplete functionality for gp-lookup

---

data/formdata.json
src/server/index.js
src/server/plugins/formdata/index.js
src/shared/lib/form-data.js

Created an endpoint to fill up form with fake data

Fakeform data created

---

src/server/plugins/register-form/steps/previously-armed.js
src/shared/lib/joi-full-date-validator.js

Full date validation in army step.

full date validation
